CREATE DATABASE AVIACAO;
USE AVIACAO;
create table TRANSPORTADORA(
CNPJ CHAR(18) NOT NULL,
NOME VARCHAR(80) NOT NULL, 
ENDERECO VARCHAR(60) NOT NULL,
PRIMARY KEY (CNPJ)
);

create table AVIAO(
MATRICULA INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(50) NOT NULL,
MODELO VARCHAR(45) NOT NULL,
AUTONOMIA INT NOT NULL,
LUGARES INT NOT NULL,
TRANSPORTADORA_CNPJ CHAR(18) NOT NULL,
PRIMARY KEY (MATRICULA),
FOREIGN KEY(TRANSPORTADORA_CNPJ) REFERENCES TRANSPORTADORA(CNPJ)
);

create table VOO(
ID INT UNSIGNED auto_increment NOT NULL,
PARTIDA VARCHAR(80) NOT NULL,
DATA DATE NOT NULL,
HORA TIME NOT NULL,
DESTINO VARCHAR(80) NOT NULL,
PILOTO_NUMERO_LICENCA INT NOT NULL,
AVIAO_MATRICULA INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY(PILOTO_NUMERO_LICENCA) REFERENCES PILOTO(NUMERO_LICENCA),
FOREIGN KEY(AVIAO_MATRICULA) REFERENCES AVIAO(MATRICULA)
);

CREATE TABLE PILOTO(
NUMERO_LICENCA INT NOT NULL,
NOME VARCHAR(80) NOT NULL,
MODELOS VARCHAR(100) NOT NULL,
TRANSPORTADORA_CNPJ CHAR(18) NOT NULL,
PRIMARY KEY (NUMERO_LICENCA),
FOREIGN KEY(TRANSPORTADORA_CNPJ) REFERENCES TRANSPORTADORA(CNPJ) 
);

CREATE TABLE DESCENDENTES(
NOME VARCHAR(80) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
PILOTO_NUMERO_LICENCA INT NOT NULL,
PRIMARY KEY (NOME),
FOREIGN KEY(PILOTO_NUMERO_LICENCA) REFERENCES PILOTO(NUMERO_LICENCA)
);


