CREATE DATABASE LOJA_TURMA;
USE LOJA_TURMA;

CREATE TABLE EMPRESAS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
TELEFONE VARCHAR(80) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
PRIMARY KEY (CODIGO)
);

INSERT INTO EMPRESAS(CODIGO, NOME, ENDERECO, TELEFONE, EMAIL)
VALUES (NULL, 'BLIZARD', 'RUA 122', '987749365', 'BLIZZARD@GMAIL.COM');
INSERT INTO EMPRESAS(CODIGO, NOME, ENDERECO, TELEFONE, EMAIL)
VALUES (NULL, 'CBF', 'RUA 20', '992934987', 'CBF@GMAIL.COM');
INSERT INTO EMPRESAS(CODIGO, NOME, ENDERECO, TELEFONE, EMAIL)
VALUES (NULL, 'XEROX', 'RUA 4', '987249843', 'XEROX.COM');
INSERT INTO EMPRESAS(CODIGO, NOME, ENDERECO, TELEFONE, EMAIL)
VALUES (NULL, 'STEAM', 'RUA 3', '9784217689', 'STEAM@GMAIL.COM');
INSERT INTO EMPRESAS(CODIGO, NOME, ENDERECO, TELEFONE, EMAIL)
VALUES (NULL, 'GILLETE', 'RUA 1', '947516899', 'GILLETE@GMAIL.COM');

CREATE TABLE CLIENTES(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
TELEFONE VARCHAR(80) NOT NULL,
CIDADE VARCHAR(80) NOT NULL,
ESTADO CHAR(2) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
PRIMARY KEY (CODIGO)
);

INSERT INTO CLIENTES(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL)
VALUES (NULL, 'LIGIA', 'RUA 091', '924563789', 'BELO HORIZONTE', 'MG', 'KLEBER@GMAIL.COM');
INSERT INTO CLIENTES(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL)
VALUES (NULL, 'JOSE', 'RUA 3221', '925784691', 'CONTAGEM', 'MG', 'JORGEDASILVA@GMAIL.COM');
INSERT INTO CLIENTES(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL)
VALUES (NULL, 'KIBELEZA', 'RUA 1002 ', '940235789','ITUMBIARA','MG', 'LISSANDRA@GMAIL.COM');
INSERT INTO CLIENTES(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL)
VALUES (NULL, 'JUBILANES', 'RUA 882', '947785213','BETIM','MG', 'JUBILEU@GMAIL.COM');
INSERT INTO CLIENTES(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL)
VALUES (NULL, 'MATHEUS', 'RUA 666', '989042278','ITUMBIARA','MG', 'MATHEUSALEXANDRE@GMAIL.COM');

CREATE TABLE LOJAS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
CIDADE VARCHAR(80) NOT NULL,
TIPO_LOJA VARCHAR(80),
EMPRESA_CODIGO INT NOT NULL,
PRIMARY KEY (CODIGO),
FOREIGN KEY (EMPRESA_CODIGO) REFERENCES  EMPRESA(CODIGO)
);

INSERT INTO LOJAS(CODIGO, NOME, ENDERECO, CIDADE, TIPO_LOJA, EMPRESA_CODIGO)
VALUES (NULL, 'GAMES DAORA', 'RUA 72', 'BELO HORIZONTE', 'JOGOS', 1);
INSERT INTO LOJAS(CODIGO, NOME, ENDERECO, CIDADE, TIPO_LOJA, EMPRESA_CODIGO)
VALUES (NULL, 'LOJA DE ROUPAS', 'RUA 13', 'CONTAGEM', 'ROUPAS', 2);
INSERT INTO LOJAS(CODIGO, NOME, ENDERECO, CIDADE, TIPO_LOJA, EMPRESA_CODIGO)
VALUES (NULL, 'PARADA GAMES', 'RUA 46','BETIM','JOGOS', 3);
INSERT INTO LOJAS(CODIGO, NOME, ENDERECO, CIDADE, TIPO_LOJA, EMPRESA_CODIGO)
VALUES (NULL, 'LOJA DO SEU JORGE', 'RUA 23','BELO HORIZONTE','ELETRODOMESTICOS', 4);
INSERT INTO LOJAS(CODIGO, NOME, ENDERECO, CIDADE, TIPO_LOJA, EMPRESA_CODIGO)
VALUES (NULL, 'PICHAU', 'RUA 58', 'BETIM','COMPUTADORES', 5);

CREATE TABLE EMPREGADOS(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
TELEFONE VARCHAR(80) NOT NULL,
CIDADE VARCHAR(80) NOT NULL,
ESTADO CHAR(2) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
LOJAS_CODIGO INT NOT NULL,
PRIMARY KEY (CODIGO),
FOREIGN KEY (LOJAS_CODIGO) REFERENCES  LOJAS(CODIGO)
);

INSERT INTO EMPREGADOS(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL, LOJAS_CODIGO)
VALUES (NULL, 'JUAREZ', 'RUA A65','923478519', 'BELO HORIZONTE', 'MG', 'ROBERT@TANIDE.COM', 1);
INSERT INTO EMPREGADOS(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL, LOJAS_CODIGO)
VALUES (NULL, 'SOAREZ', 'A1','945788129', 'CONTAGEM','MG', 'TANIDE@ROBERT.COM', 2);
INSERT INTO EMPREGADOS(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL, LOJAS_CODIGO)
VALUES (NULL, 'ENZO', 'RUA B104','9547786321','ITAUNA','MG','JOAO@ALEXANDRE.COM', 3);
INSERT INTO EMPREGADOS(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL, LOJAS_CODIGO)
VALUES (NULL, 'ALE', 'RUA U35','925789863','BELO HORIZONTE','MG','ALEXANDRE@JOAO.COM', 4);
INSERT INTO EMPREGADOS(CODIGO, NOME, ENDERECO, TELEFONE, CIDADE, ESTADO, EMAIL, LOJAS_CODIGO)
VALUES (NULL, 'RETORV', 'RUA N132','944577812', 'BETIM','MG','ROBERTOSILVEIRA@GMAIL.COM', 5);

CREATE TABLE PRODUTOS(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
DESCRICAO VARCHAR(80) NOT NULL,
VALOR DOUBLE(9,2) NOT NULL,
QUANTIDADE INTEGER NOT NULL,
OBSERVACAO VARCHAR(80) NOT NULL,
LOJAS_CODIGO INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (LOJAS_CODIGO) REFERENCES  LOJAS(CODIGO)
);

INSERT INTO PRODUTOS(ID, DESCRICAO, VALOR, QUANTIDADE, OBSERVACAO, LOJAS_CODIGO)
VALUES (NULL, 'SACOLA', 1235.00, 1200,'FEITO DE PRATA', 1);
INSERT INTO PRODUTOS(ID, DESCRICAO, VALOR, QUANTIDADE, OBSERVACAO, LOJAS_CODIGO)
VALUES (NULL, 'PRESERVATIVO', 21554.00, 7700,'BANHADO COM O DIAMANTE NEGRO', 2);
INSERT INTO PRODUTOS(ID, DESCRICAO, VALOR, QUANTIDADE, OBSERVACAO, LOJAS_CODIGO)
VALUES (NULL, 'FIFA', 666.00, 666,'PRODUTO COM ALTAS CHANCES DE FALSIFICAÇÃO', 3);
INSERT INTO PRODUTOS(ID, DESCRICAO, VALOR, QUANTIDADE, OBSERVACAO, LOJAS_CODIGO)
VALUES (NULL, 'PENEIRA', 170.00, 55,'PODE QUEBRAR COM FACILIDADE', 4);
INSERT INTO PRODUTOS(ID, DESCRICAO, VALOR, QUANTIDADE, OBSERVACAO, LOJAS_CODIGO)
VALUES (NULL, 'MOTOR', 145.00, 70,'CASO SEJA SOCADO ELE PODE QUEBRAR', 5);

CREATE TABLE VENDAS(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
DATA DATE NOT NULL,
TOTAL DOUBLE(9,2) NOT NULL,
HORA TIME NOT NULL,
OBSERVACAO VARCHAR(80) NOT NULL,
LOJAS_CODIGO INT NOT NULL,
CLIENTES_CODIGO INT NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (LOJAS_CODIGO) REFERENCES  LOJAS(CODIGO),
FOREIGN KEY (CLIENTES_CODIGO) REFERENCES  CLIENTES(CODIGO)
);

INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_CODIGO, CLIENTES_CODIGO)
VALUES (NULL, '20190522', 1300, '5:43', 'VENDA APROVADA',2,2);
INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_CODIGO, CLIENTES_CODIGO)
VALUES (NULL, '20190522', 1300, '5:43', 'VENDA APROVADA',2,2);
INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_CODIGO, CLIENTES_CODIGO)
VALUES (NULL, '90210', 1400, '2:25', 'VENDA APROVADA',3,3);
INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_CODIGO, CLIENTES_CODIGO)
VALUES (NULL, '20327', 1700, '2:43', 'VENDA APROVADA',4,4);
INSERT INTO VENDAS(ID, DATA, TOTAL, HORA, OBSERVACAO, LOJAS_CODIGO, CLIENTES_CODIGO)
VALUES (NULL, '116', 1100, '19:11', 'VENDA APROVADA',5,5);

CREATE TABLE ITENS_VENDA(
NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
VALOR_UNITARIO DOUBLE(9,2) NOT NULL,
QUANTIDADE INT NOT NULL,
VENDAS_ID INT NOT NULL,
PRODUTOS_ID INT NOT NULL,
PRIMARY KEY (NUMERO),
FOREIGN KEY (VENDAS_ID) REFERENCES  VENDAS(ID),
FOREIGN KEY (PRODUTOS_ID) REFERENCES  PRODUTOS(ID)
);

INSERT INTO ITENS_VENDA(NUMERO, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID)
VALUES (NULL, 5000, 1390,1,1);
INSERT INTO ITENS_VENDA(NUMERO, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID)
VALUES (NULL, 777, 777,2,2);
INSERT INTO ITENS_VENDA(NUMERO, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID)
VALUES (NULL, 1050, 370,3,3);
INSERT INTO ITENS_VENDA(NUMERO, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID)
VALUES (NULL, 75, 13607,4,4);
INSERT INTO ITENS_VENDA(NUMERO, VALOR_UNITARIO, QUANTIDADE, VENDAS_ID, PRODUTOS_ID)
VALUES (NULL, 15700, 2070,5,5);


DELETE FROM ITENS_VENDA WHERE VALOR_UNITARIO > 100;
SELECT * FROM LOJAS WHERE TIPO_LOJA = 'SUPERMERCADO';
SELECT * FROM CLIENTES WHERE ESTADO = 'SP';
SELECT * FROM PRODUTOS WHERE VALOR > 200;
SELECT * FROM PRODUTOS WHERE QUANTIDADE > 20;
SELECT * FROM LOJAS WHERE EMPRESA_CODIGO = 2;
SELECT AVG(TOTAL) FROM VENDAS WHERE HORA < '22:00' && HORA > '19:00';
SELECT NOME, ENDERECO FROM CLIENTES WHERE ESTADO = 'SP' || ESTADO = 'MG';
SELECT * FROM ITENS_VENDA WHERE QUANTIDADE >10;
SELECT * FROM ITENS_VENDA WHERE QUANTIDADE >2 && QUANTIDADE <5;
SELECT AVG(VALOR_UNITARIO) FROM ITENS_VENDA WHERE VALOR_UNITARIO >3;
SELECT DESCRICAO, VALOR, QUANTIDADE FROM PRODUTOS WHERE ID > 15 && ID <30;
DELETE FROM ITENS_VENDA WHERE VALOR_UNITARIO < 1;