CREATE DATABASE HOTELARIA_TURMA;
USE HOTELARIA_TURMA;

CREATE TABLE CLIENTE(
COD INTEGER NOT NULL AUTO_INCREMENT,
NOME VARCHAR(80) NOT NULL,
CPF INT,
TIPO_CONVENIO VARCHAR(40) NOT NULL,
PRIMARY KEY (COD)
);

INSERT INTO CLIENTE(COD,NOME,CPF,TIPO_CONVENIO)
VALUES (NULL,'JOSE SILVA',1235678,'VIP');
INSERT INTO CLIENTE(COD,NOME,CPF,TIPO_CONVENIO)
VALUES (NULL,'ANTONIO',32135678,'VIP');
INSERT INTO CLIENTE(COD,NOME,CPF,TIPO_CONVENIO)
VALUES (NULL,'JOSE SILVA',42115678,'VIP');

CREATE TABLE SERVICO_COPA(
COD INTEGER NOT NULL AUTO_INCREMENT,
REGISTRO VARCHAR(100) NOT NULL,
TIPO_SERVICO VARCHAR(40) NOT NULL,
PRIMARY KEY (COD)
);

INSERT INTO SERVICO_COPA(COD,REGISTRO,TIPO_SERVICO)
VALUES(NULL,123,"TOP 1");
INSERT INTO SERVICO_COPA(COD,REGISTRO,TIPO_SERVICO)
VALUES(NULL,321,"TOP 2");


CREATE TABLE RESERVA(
COD INTEGER NOT NULL AUTO_INCREMENT,
DATAINICIO DATE NOT NULL,
DATAFIM DATE NOT NULL,
QUARTO INT NOT NULL,
VALOR DOUBLE(9,2) NOT NULL,
CLIENTE_COD INTEGER NOT NULL,
PRIMARY KEY (COD),
FOREIGN KEY (CLIENTE_COD) REFERENCES CLIENTE(COD)
);

INSERT INTO RESERVA(cod,datainicio,datafim,quarto,valor,cliente_cod) 
VALUES(null,32121001,5121010,1,150.00,2);
INSERT INTO RESERVA(cod,datainicio,datafim,quarto,valor,cliente_cod) 
VALUES(null,1001,21010,1,120.00,2);
INSERT INTO RESERVA(cod,datainicio,datafim,quarto,valor,cliente_cod) 
VALUES(null,32121001,35121010,1,150.00,2);

CREATE TABLE HOSPEDE(
COD INTEGER NOT NULL AUTO_INCREMENT,
NOME VARCHAR(80) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
RESERVA_COD INTEGER NOT NULL,
PRIMARY KEY (COD),
FOREIGN KEY (RESERVA_COD) REFERENCES RESERVA(COD)
);

INSERT INTO HOSPEDE(COD,NOME,TELEFONE,EMAIL,RESERVA_COD)
VALUES(NULL,'LUIZ HENRIQUE',2111212,'LUIZ@GMAIL.COM',12);
INSERT INTO HOSPEDE(COD,NOME,TELEFONE,EMAIL,RESERVA_COD)
VALUES(NULL,'PEDRO JOSE',212212,'ASLL1@GMAIL.COM',33);
INSERT INTO HOSPEDE(COD,NOME,TELEFONE,EMAIL,RESERVA_COD)
VALUES(NULL,'ALMEIDA JUNIOR',3111212,'PPPQ1@GMAIL.COM',22);

CREATE TABLE QUARTO(
COD INTEGER NOT NULL AUTO_INCREMENT,
NUMERO INT NOT NULL,
ANDAR INT NOT NULL,
CLASSIFICACAO VARCHAR(40),
HOSPEDE_COD INTEGER NOT NULL,
PRIMARY KEY (COD),
FOREIGN KEY (HOSPEDE_COD) REFERENCES HOSPEDE(COD)
);

INSERT INTO QUARTO(COD,NUMERO,ANDAR,CLASSIFICACAO,HOSPEDE_COD)
VALUES(NULL,1,2,"3 ESTRELAS",1);
INSERT INTO QUARTO(COD,NUMERO,ANDAR,CLASSIFICACAO,HOSPEDE_COD)
VALUES(NULL,2,3,"4 ESTRELAS",2);
INSERT INTO QUARTO(COD,NUMERO,ANDAR,CLASSIFICACAO,HOSPEDE_COD)
VALUES(NULL,3,3,"5 ESTRELAS",3);

CREATE TABLE SERVICOS(
COD INTEGER NOT NULL AUTO_INCREMENT,
ITENS VARCHAR(50) NOT NULL,
TIPO VARCHAR(50) NOT NULL,
OBSERVACAO VARCHAR(100) NOT NULL,
QUARTO_COD INTEGER NOT NULL,
SERVICO_COPA_COD INTEGER NOT NULL,
PRIMARY KEY (COD),
FOREIGN KEY (QUARTO_COD) REFERENCES QUARTO(COD),
FOREIGN KEY (SERVICO_COPA_COD) REFERENCES SERVICO_COPA(COD)
);

INSERT INTO SERVICOS(COD,ITENS,TIPO,OBSERVACAO,QUARTO_COD,SERVICO_COPA_COD)
VALUES(NULL,'FLOR','AMARELA','BOM',1,2);
INSERT INTO SERVICOS(COD,ITENS,TIPO,OBSERVACAO,QUARTO_COD,SERVICO_COPA_COD)
VALUES(NULL,'PANO','AZUL','ARABE',5,11);
INSERT INTO SERVICOS(COD,ITENS,TIPO,OBSERVACAO,QUARTO_COD,SERVICO_COPA_COD)
VALUES(NULL,'CHAO','AZUL','CARAMELO',41,72);
INSERT INTO SERVICOS(COD,ITENS,TIPO,OBSERVACAO,QUARTO_COD,SERVICO_COPA_COD)
VALUES(NULL,'PAREDE','ROXA','MARAVILHOSO',55,11232);


DELETE FROM RESERVAS WHERE VALOR > 100;
DELETE FROM HOSPEDE;
UPDATE RESERVA SET VALOR = 100 WHERE DATAINICIO = "2019-06-06";
SELECT * FROM RESERVA WHERE DATAINICIO BETWEEN "2019-05-01" AND "2019-06-01";
SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) FROM QUARTO WHERE ANDAR = 2;
SELECT AVG(VALOR) FROM RESERVA;
SELECT NOME, CPF FROM CLIENTE;
SELECT * FROM SERVICOS WHERE TIPO="ALMOÇO";
SELECT SUM(VALOR) FROM RESERVA;
SELECT NOME, TELEFONE, EMAIL FROM HOSPEDE ORDER BY NOME;
DELETE FROM SERVICO_COPA WHERE COD < 10;
SELECT NOME, TELEFONE FROM HOSPEDE WHERE COD BETWEEN 15 AND 20;
SELECT registro, tipo_servico FROM servico_copa ORDER BY COD;
SELECT COUNT(*) FROM servico WHERE tipo = "Limpeza";
SELECT itens, tipo FROM servico WHERE quarto_cod = 2;
SELECT AVG(valor) FROM reserva WHERE quarto = 4;
UPDATE reserva SET datainicio = "2013-04-01" WHERE quarto = 8;
DELETE FROM reserva WHERE valor < 35;
DELETE FROM servico WHERe cod != 150;


