CREATE DATABASE IMOBILIARIA_TURMA;
USE IMOBILIARIA_TURMA;

CREATE TABLE IMOBILIARIA(
CNPJ CHAR(17) NOT NULL,
NOME VARCHAR(90) NOT NULL,
ENDERECO VARCHAR(45) NOT NULL,
PRIMARY KEY (CNPJ)
);

INSERT INTO IMOBILIARIA(CNPJ,NOME,ENDERECO)
VALUES('10','Soares','Rua Helio');
INSERT INTO IMOBILIARIA(CNPJ,NOME,ENDERECO)
VALUES('22','Juares','Rua Zelio');
INSERT INTO IMOBILIARIA(CNPJ,NOME,ENDERECO)
VALUES('13','Cuares','Rua Quelio');


CREATE TABLE CORRETOR(
CRECI INTEGER NOT NULL,
NOME VARCHAR(80),
DTAMISSAO DATE NOT NULL,
PRIMARY KEY (CRECI)
);

INSERT INTO CORRETOR(CRECI,NOME,DTAMISSAO)
VALUES('2111','Gilson','2019/11/12');
INSERT INTO CORRETOR(CRECI,NOME,DTAMISSAO)
VALUES('3111','Nilson','2018/12/11');
INSERT INTO CORRETOR(CRECI,NOME,DTAMISSAO)
VALUES('4111','Gilson','2011/11/14');


CREATE TABLE COMPRADOR(
CPF CHAR(11) NOT NULL,
NOME VARCHAR(80) NOT NULL,
PROFISSAO VARCHAR(60) NOT NULL,
LISTAMOVEIS VARCHAR(100) NOT NULL,
PRIMARY KEY (CPF)
);

INSERT INTO COMPRADOR(CPF,NOME,PROFISSAO,LISTAMOVEIS)
VALUES('12321','Farlen','MestreDoBD','Jaraguar');
INSERT INTO COMPRADOR(CPF,NOME,PROFISSAO,LISTAMOVEIS)
VALUES('31321','Thiagao','MestreDaoCsharp','Netoland');

CREATE TABLE PROPIETARIO(
CPF CHAR(11) NOT NULL,
NOME VARCHAR(80) NOT NULL,
ESTADOCIVIL CHAR(1) NOT NULL,
CONJUGUE VARCHAR(80) NOT NULL,
PRIMARY KEY (CPF)
);

INSERT INTO PROPIETARIO(CPF,NOME,ESTADOCIVIL,CONJUGUE)
VALUES('2211','Arhtur','s','mão');
INSERT INTO PROPIETARIO(CPF,NOME,ESTADOCIVIL,CONJUGUE)
VALUES('1122','Antonio','c','Maria');

CREATE TABLE ENDERECO(
CODIGO INTEGER NOT NULL AUTO_INCREMENT,
NUMERO INTEGER NOT NULL,
RUA VARCHAR(80) NOT NULL,
BAIRRO VARCHAR(60) NOT NULL,
CEP CHAR(11) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
PRIMARY KEY (CODIGO)
);

INSERT INTO ENDERECO(CODIGO,NUMERO,RUA,BAIRRO,CEP,TELEFONE)
VALUES(NULL,'21','RUA ALMEIDA','TUPI','2111','312211');
INSERT INTO ENDERECO(CODIGO,NUMERO,RUA,BAIRRO,CEP,TELEFONE)
VALUES(NULL,'31','RUA CUNHA','Zavazi','3221','332211');

CREATE TABLE VENDA(
CODIGO INTEGER NOT NULL AUTO_INCREMENT,
COMISSAO INTEGER NOT NULL,
DATA DATE NOT NULL,
VALOR DOUBLE(9,2),
IMOBILIARIA_CNPJ CHAR(17) NOT NULL,
IMOVEL_INSCRICAO INTEGER NOT NULL,
CORRETOR_CRECI INTEGER NOT NULL,
COMPRADOR_CPF CHAR(11) NOT NULL,
PRIMARY KEY (CODIGO),
FOREIGN KEY (IMOBILIARIA_CNPJ) REFERENCES IMOBILIARIA(CNPJ),
FOREIGN KEY (IMOVEL_INSCRICAO) REFERENCES IMOVEL(INSCRICAO),
FOREIGN KEY (CORRETOR_CRECI) REFERENCES CORREOTR(CRECI),
FOREIGN KEY (COMPRADOR_CPF) REFERENCES COMPRADOR(CPF) 
);

INSERT INTO VENDA(CODIGO,COMISSAO,DATA,VALOR,IMOBILIARIA_CNPJ,IMOVEL_INSCRICAO,CORRETOR_CRECI,COMPRADOR_CPF)
VALUES(NULL,'311','2015/05/01','332','11','11','11','11');
INSERT INTO VENDA(CODIGO,COMISSAO,DATA,VALOR,IMOBILIARIA_CNPJ,IMOVEL_INSCRICAO,CORRETOR_CRECI,COMPRADOR_CPF)
VALUES(NULL,'441','2011/01/11','555','22','31','22','44');

CREATE TABLE IMOVEL(
INSCRICAO INTEGER NOT NULL,
AREA_TOTAL INTEGER NOT NULL,
AREA_CONSTRUIDA INTEGER NOT NULL,
VR_VENDA DOUBLE(9,2) NOT NULL,
ENDERECO_CODIGO INTEGER NOT NULL,
IMOBILIARIA_CNPJ CHAR(17) NOT NULL,
PROPIETARIO_CPF CHAR(11) NOT NULL,
PRIMARY KEY (INSCRICAO),
FOREIGN KEY (ENDERECO_CODIGO) REFERENCES ENDERECO(CODIGO),
FOREIGN KEY (IMOBILIARIA_CNPJ) REFERENCES IMOBILIARIA(CNPJ),
FOREIGN KEY (PROPIETARIO_CPF) REFERENCES PROPIETARIO(CPF)
);

INSERT INTO IMOVEL(INSCRICAO,AREA_TOTAL,AREA_CONSTRUIDA,VR_VENDA,ENDERECO_CODIGO,IMOBILIARIA_CNPJ,PROPIETARIO_CPF)
VALUES('111','31321','1111','50000','33221','11133222','11122233');
INSERT INTO IMOVEL(INSCRICAO,AREA_TOTAL,AREA_CONSTRUIDA,VR_VENDA,ENDERECO_CODIGO,IMOBILIARIA_CNPJ,PROPIETARIO_CPF)
VALUES('532','4421','55511','89500','44421','41111121','44112233');

/*10) Deletar todas as vendas com código maior que 10.---
11) Selecionar todos compradores --
12) Selecionar todos endereços com numero menor que 200--
13) Selecionar os imóveis com valor de venda igual a 100000.-
14) Selecionar o nome e endereço da imobiliária----
15) Selecionar a media de valor das vendas com data entre março de 2013 e abril de 2013---
16) Selecionar o somatório de valor das vendas com código maior que 30----
17) Atualizar na imobiliária o endereço para rua amazonas onde o nome for “imobiliária x”-----
18) Deletar todos endereços com numero entre 10 e 230----
19) Selecionar a venda de maior valor---
20) Selecionar a venda de menor valor----
21) Selecionar quantos corretores existem---
22) Selecionar quantos proprietários existem com estado civil  “solteiro”----
*/

DELETE FROM VENDA WHERE CODIGO > 10;
SELECT * FROM COMPRADOR;
SELECT * FROM ENDERECO WHERE NUMERO < 200;
SELECT * FROM IMOVEL WHERE VR_VENDA = 100000;
SELECT NOME,ENDERECO FROM IMOBILIARIA;
SELECT AVG(VALOR) FROM VENDA WHERE DATA BETWEEN "2013/04/30" AND "2013/04/30";
SELECT SUM(VALOR) FROM VENDA WHERE CODIGO > 30;
UPDATE IMOBILIARIA SET ENDERECO="RUA AMAZONAS" WHERE NOME = 'IMOBILIARIA X';
DELETE FROM ENDERECO WHERE NUMERO  BETWEEN 10 AND 230;  
SELECT MAX(VALOR) FROM VENDA;
SELECT MIN(VALOR) FROM VENDA;
SELECT COUNT(*) FROM CORRETOR;
SELECT * FROM PROPIETARIO WHERE ESTADOCIVIL = 'Solteiro';