CREATE DATABASE BDLOGIN;
USE BDLOGIN;
CREATE TABLE ALUNO(
MATRICULA INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
SEXO char(1) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(150) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
PRIMARY KEY(MATRICULA)
);

CREATE TABLE PROFESSOR(
NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
SEXO CHAR(1) NOT NULL,
EMAIL VARCHAR(80) NOT null,
ENDERECO VARCHAR(150) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
PRIMARY KEY(NUMERO)
);

CREATE TABLE CURSO(
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(60) NOT NULL,
SERIE VARCHAR(10),
PRIMARY KEY(CODIGO)
);

CREATE TABLE FUNCIONARIO(
MATRICULA INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
SEXO CHAR(1) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(150) NOT NULL,
TELEFONE CHAR(15) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
SETOR VARCHAR(20),
PRIMARY KEY(MATRICULA)
);

CREATE TABLE NOTAS(
NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
PROVA VARCHAR(50) NOT NULL,
NOTA DOUBLE(9,2) NOT NULL,
ALUNO_MATRICULA INT UNSIGNED NOT NULL,
PROFESSOR_NUMERO INT UNSIGNED NOT NULL,
PRIMARY KEY (NUMERO),
foreign key(ALUNO_MATRICULA) references ALUNO(MATRICULA),
foreign key(PROFESSOR_NUMERO) references PROFESSOR(NUMERO)
);

CREATE TABLE DISCIPLINA(
NUMERO INT unsigned auto_increment NOT NULL,
NOME VARCHAR(80) NOT NULL,
CONTEUDO VARCHAR(150) NOT NULL,
TURMA VARCHAR(80) NOT NULL,
PROFESSOR_NUMERO INT unsigned NOT NULL,
CURSO_CODIGO INT UNSIGNED NOT NULL,
PRIMARY KEY(NUMERO),
foreign key(PROFESSOR_NUMERO) references PROFESSOR(NUMERO),
foreign key(CURSO_CODIGO) references CURSO(CODIGO)
);

