CREATE DATABASE ELEITORAL;
USE ELEITORAL;

CREATE TABLE LOCALIDADE(
ID INT unsigned auto_increment NOT NULL,
NOME VARCHAR(80) NOT NULL,
REGIAO VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ZONAS_ELEITORAIS(
ID INT UNSIGNED auto_increment NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE SECOES(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
DESCRICAO VARCHAR(120) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ELEITOR(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE VOTO(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
DATA DATE NOT NULL,
QUANTIDADE DOUBLE(9,4),
PRIMARY KEY(ID)
);

CREATE TABLE CARGO(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
DESCRICAO VARCHAR(120) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE CANDIDATO(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE PARTIDO(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
SIGLA VARCHAR(10) NOT NULL,
NOME VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);




