CREATE DATABASE FLORES;
USE FLORES;

CREATE TABLE CLIENTE(
CPF CHAR(18) NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
PRIMARY KEY(CPF)
);

CREATE TABLE FLORES(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
TIPO VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE CIDADES(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
REGIAO VARCHAR(80) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE FLORICULTURA(
CNPJ CHAR(19) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
NOME VARCHAR(80) NOT NULL,
PRIMARY KEY(CNPJ)
);

CREATE TABLE XPTO(
CNPJ CHAR(19) NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(80) NOT NULL,
PRIMARY KEY(CNPJ)
);

CREATE TABLE COMPRAR(
CLIENTE_CPF CHAR(18) NOT NULL,
FLORES_ID INT unsigned NOT NULL,
DATA DATE NOT NULL,
VALOR DOUBLE(9,4) NOT NULL,
foreign key(CLIENTE_CPF) references CLIENTE(CPF),
FOREIGN KEY(FLORES_ID) REFERENCES FLORES(ID)
);

