/* criar o banco de dados*/
CREATE DATABASE SISTEMABANCARIO;
/* DEFINIR BANCO DE DADOS*/
USE SISTEMABANCARIO;
/* CRIAR TABELAS */

CREATE TABLE AGENCIA(
/*UNSIGNED > NUMERO SEM SINAL /NAO ACEITA NEGATIVO AUTO_INCREMENT > GERAR GODIGO AUTOMATICO /SOMENTE CHAVE PRIMAIRA INT*/
CODIGO INT UNSIGNED AUTO_INCREMENT NOT NULL,
NOME VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(120) NOT NULL,
GERENTE VARCHAR(80) NOT NULL,
PRIMARY KEY(CODIGO)
);

CREATE TABLE CLIENTE(
CPF CHAR(14) NOT NULL,
NOME VARCHAR(80) NOT NULL,
RG VARCHAR(15) NOT NULL,
ESTADO_CIVIL VARCHAR(15) NOT NULL,
PRIMARY KEY (CPF)
);

CREATE TABLE CONTAS(
NUMERO INT UNSIGNED AUTO_INCREMENT NOT NULL,
SALDO DOUBLE(9,2) NOT NULL,
AGENCIA_CODIGO INT UNSIGNED NOT NULL,
CLIENTE_CPF CHAR(14) NOT NULL,
PRIMARY KEY(NUMERO),
FOREIGN KEY(AGENCIA_CODIGO) REFERENCES AGENCIA (CODIGO),
FOREIGN KEY(CLIENTE_CPF) REFERENCES CLIENTE0(CPF)
);

CREATE TABLE MOVIMENTACAO(
CONTAS_NUMERO INT UNSIGNED NOT NULL,
CLIENTE_CPF CHAR(14) NOT NULL,
QUANTIA DOUBLE(9,2) NOT NULL,
DATA DATE NOT NULL,
HORA TIME NOT NULL,
TIPO CHAR(1) NOT NULL,
PRIMARY KEY(CONTAS_NUMERO, CLIENTE_CPF),
FOREIGN KEY(CONTAS_NUMERO) REFERENCES CONTAS(NUMERO),
FOREIGN KEY(CLIENTE_CPF) REFERENCES CLIENTES(CPF)
);